title: Sensical-Math (WIP)
description: A project developed to help UIL Number Sense competitors practice arithmetic and NS problems via a website.
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
